### ISSUE TITLE
 how to run the example,

### ISSUE THREAD

**Issue by SeekPoint** [cytoscape/py2cytoscape#80]
ub16hp@UB16HP:/media/ub16hp/WINDOWS/ub16_prj/py2cytoscape/examples$ python3 samples_for_v0.6.0.py 
<IPython.core.display.Javascript object>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

**Comment by jorgeboucas** [comment]
please try updating to python 3.6.

**Comment by SeekPoint** [comment]
C:\ub16_prj\py2cytoscape\examples>python samples_for_v0.6.0.py
To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.
py2cytoscape: Error importing igraph. You won't be able to import from igraph.
<IPython.core.display.Javascript object>
Traceback (most recent call last):
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by zachary822** [comment]
Do you have the Cytoscape desktop program running? What version are you using?

**Comment by victoriastuart** [comment]
... connection refused ... Do you have the Cytoscape desktop program running? << this should be added to the docs ...

**Comment by jorgeboucas** [comment]
Apart from making sure you have Cytoscape running it might be that the jump to python 3.7 was a bit too much. I would follow @zachary822 recommendation and try it on 3.6.

**Comment by glennccc** [comment]
Why don't you just write a simple example about how to use py2cytoscape? I can not learn any useful getting started about your README.md

**Comment by matthiaskoenig** [comment]
It seems to me the py2cytoscape project is deprecated and you should have a look at py4cytoscape
https://github.com/cytoscape/py4cytoscape
With documentation here: https://py4cytoscape.readthedocs.io/en/latest/
and examples here: https://py4cytoscape.readthedocs.io/en/latest/tutorials/index.html

**Comment by bdemchak** [comment]
Hi ...

With apologies... py2cytoscape has been deprecated. We will put a notice on
this report.

In the meantime, would you mind trying py4cytoscape??

https://pypi.org/project/py4cytoscape/

https://github.com/cytoscape/py4cytoscape


... sent from my mobile phone ... please forgive my typos.

vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
: Barry Demchak, PhD                   :
: Torrey Pines Software, Inc.          :
: http://www.tpsoft.com/               :
: http://orcid.org/0000-0001-7065-7786 :
: (858) 452-8700                       :
: (619) 218-3717 (cell/text)           :
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

**Comment by bdemchak** [comment]
Thanks, Matthias … I have added a deprecation message and forwarding link to the py2cytoscape README page.
